apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  bitcoin-core22
  labels:
    name:  bitcoin-core22
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  Bitcoin_core22
    spec:
      containers:
      - image: lightninglabs/bitcoin-core:22-alpine #image sourced from lightninglabs repo on dockerhub
        name:  bitcoin_core22
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  MYSQL_DB
          value:  DB_ADMIN       
        ports:
        - containerPort:  5000
          name:  bitcoin-core22
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
